<<<<<<< HEAD
# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Thinny
tagline:	'blog'
description:	'My personal blog.'
url:		http://jslvtr.github.io/ac32007

author:
  name:		'Ian Camporez Brunelli'
  url:		https://google.com/+IanCamporezBrunelli

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/iancamporez
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/camporez
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://google.com/+IanCamporezBrunelli
    desc:	Add me on google+

  - icon:	feed
    url:	http://camporez.com/atom.xml
    desc:	Subscribe to my feed

menu:
  - title:	Home
    url:	http://jslvtr.github.io/ac32007/

  - title:	About
    url:	http://jslvtr.github.io/ac32007/about

copyright:
  author:	Camporez
  url:		http://camporez.com
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
=======
# Site settings
title: AC32007
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "http://jslvtr.github.io/ac32007" # the subpath of your site, e.g. /blog/
url: "http://jslvtr.github.io/ac32007" # the base hostname & protocol for your site
twitter_username: jslvtr
github_username:  jslvtr

# Build settings
markdown: redcarpet
>>>>>>> c2832c4... updateing url to remove /
